//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Phone { get; set; }
        public string IdentityNo { get; set; }
        public string Email { get; set; }
        public string LowerEmail { get; set; }
        public Nullable<int> AuthorizeNumberId { get; set; }
    
        public virtual AuthorizedNumber AuthorizedNumber { get; set; }
        public virtual Role Role { get; set; }
    }
}
