//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _DataLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialExam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrialExam()
        {
            this.TrialExamResults = new HashSet<TrialExamResult>();
        }
    
        public int TrialExamId { get; set; }
        public Nullable<short> Session { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string TrialExamName { get; set; }
        public Nullable<int> LessonId { get; set; }
        public string TrialExamDescription { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrialExamResult> TrialExamResults { get; set; }
    }
}
